name: run workflows for goland

on:
  push:
    branches:
      - master
    paths:
      - "image/**" # run the action when: the image has been modified
      - ".github/workflows/**" # run the action when: the workflow has been modified
jobs:
  build-goland:
    uses: ./.github/workflows/build-and-push.yaml
    with:
      IDE: goland
      IDE_SHORT: goland
      IDE_CODE: go