name: build & push
on:
  workflow_call:
    inputs:
      IDE:
        required: true
        type: string
      IDE_SHORT:
        required: true
        type: string
      IDE_CODE:
        required: true
        type: string
      IDE_VERSION:
        required: false
        type: string
        default: "2023.1.2"
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: ./image
          build-args: |
            IDE=${{ inputs.IDE }}
            IDE_SHORT=${{ inputs.IDE_SHORT }}
            IDE_CODE=${{ inputs.IDE_CODE }}
            IDE_VERSION=${{ inputs.IDE_VERSION }}
          tags: |
            ghcr.io/janisz/indexer:${{ inputs.IDE_SHORT }}-${{ inputs.IDE_VERSION }}
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
